// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
void __swift_bridge__$on_initialized(bool success);
void __swift_bridge__$on_ad_loaded(void* ad_type);
void __swift_bridge__$on_ad_failed_to_load(void* ad_type, void* error);
void __swift_bridge__$on_ad_opened(void* ad_type);
void __swift_bridge__$on_ad_closed(void* ad_type);
void __swift_bridge__$on_rewarded_ad_earned_reward(int32_t amount, void* type_name);
void __swift_bridge__$on_consent_gathered(void* error);


